# Generated by Django 2.2.6 on 2019-10-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageHandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='0000000', max_length=300),
        ),
    ]
